# Parameters/constants relative to cosmogenic nuclide production and loss
# Used in BedrockCosmogenicProducer and CosmogenicProductionScaler
e_folding_length_in_rock_spallation_g_cm2: 160.0
e_folding_length_in_rock_muon_slow_g_cm2: 1500.0
e_folding_length_in_rock_muon_fast_g_cm2: 4320.0
e_folding_length_in_air_muon_slow_g_cm2: 260.0
e_folding_length_in_air_muon_fast_g_cm2: 510.0
decay_half_life_Be10_y: 1.39e6
slhl_prod_rate_Be10_quartz_spallation_atom_g_y: 4.06
slhl_prod_rate_Be10_quartz_muon_slow_atom_g_y: 0.012
slhl_prod_rate_Be10_quartz_muon_fast_atom_g_y: 0.039
steady_state_time_to_reach_factor: 5